apiVersion: v1
kind: Secret
metadata:
  name: pg-pass
data:
  password: U2VjcmV0UGFzc3dvcmQ= # SecretPassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: registratura
spec:
  ports:
    - port: 5432
  selector:
    app: registratura
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: registratura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: registratura
spec:
  selector:
    matchLabels:
      app: registratura
      tier: db
  template:
    metadata:
      labels:
        app: registratura
        tier: db
    spec:
      containers:
        - image: postgres:14
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: registratura
spec:
  ports:
    - port: 8888
  selector:
    app: registratura
    tier: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: registratura
spec:
  selector:
    matchLabels:
      app: registratura
      tier: app
  template:
    metadata:
      labels:
        app: registratura
        tier: app
    spec:
      containers:
        - image: ghcr.io/7even/registratura:latest
          name: registratura
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 8888
              name: registratura
      imagePullSecrets:
        - name: ghcr-creds
