apiVersion: v1
kind: Service
metadata:
  name: registratura-postgres
  labels:
    app: registratura
spec:
  ports:
    - port: 5432
  selector:
    app: registratura
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: registratura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registratura-postgres
  labels:
    app: registratura
spec:
  selector:
    matchLabels:
      app: registratura
      tier: db
  template:
    metadata:
      labels:
        app: registratura
        tier: db
    spec:
      containers:
        - image: postgres:14
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
